### ISSUE TITLE
Make debian package

### ISSUE THREAD

**Issue by Theosakamg** [colcon/colcon-bazel#8]
Based on https://github.com/ros-infrastructure/ros_release_python (thanks @dirk-thomas).

`colcon_ws/src/colcon-bazel (master)$ ../../ros_release_python/scripts/ros_release_python deb3`

**Comment by Theosakamg** [comment]
Note :
- Description doesn't interpret Markdown
- Size (compressed) to 0

**Comment by dirk-thomas** [comment]
@Theosakamg Should this also be released into Ubuntu Focal?
